title: Eugene Efimov's blog
email: e.effimov@mail.ru
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://jeniaefimov.github.io"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache

author:
  name     : "Eugene Efimov"
  avatar   : "/assets/images/bio-photo.png"
  location : "Warsaw, Poland"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/eugeneefimov3"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeniaefimov"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/efimoveugenie/"
